# Generated by Django 3.2 on 2021-04-22 00:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='date_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date login'),
        ),
        migrations.AddField(
            model_name='user',
            name='date_logout',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date logout'),
        ),
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_created',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_user_created_id', to=settings.AUTH_USER_MODEL, verbose_name='Created by '),
        ),
        migrations.AddField(
            model_name='user',
            name='user_updated',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_user_updated_id', to=settings.AUTH_USER_MODEL, verbose_name='Updated by '),
        ),
        migrations.AlterField(
            model_name='user',
            name='cpf',
            field=models.CharField(help_text='Required. 11 digits exactly', max_length=11, unique=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
