# Generated by Django 3.2 on 2021-06-10 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='number_contract',
            field=models.CharField(blank=True, max_length=100, verbose_name='Number Contract'),
        ),
        migrations.AddField(
            model_name='contract',
            name='number_months',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Number of Months'),
        ),
        migrations.AddField(
            model_name='contract',
            name='pay_day',
            field=models.DateField(blank=True, default='1950-01-01', max_length=100, verbose_name='Payment Day'),
        ),
        migrations.AddField(
            model_name='contract',
            name='value_month',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, verbose_name='Value Month'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='object',
            field=models.TextField(verbose_name='Object'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Contract Value'),
        ),
    ]
