# Generated by Django 3.2 on 2021-06-18 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0003_alter_contract_pay_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Contract Value'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='value_month',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, verbose_name='Value Month'),
        ),
    ]
