# Generated by Django 3.2 on 2021-06-18 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0004_auto_20210618_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='dt_conclusion',
            field=models.DateField(blank=True, default='1950-01-01', max_length=100, verbose_name='Date End'),
        ),
    ]
