# Generated by Django 3.2 on 2021-06-18 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0007_alter_contract_dt_conclusion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='dt_conclusion',
            field=models.DateField(blank=True, max_length=100, null=True, verbose_name='Date End'),
        ),
    ]
