# Generated by Django 3.2 on 2021-06-24 12:45

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0002_alter_provider_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contract', '0008_alter_contract_dt_conclusion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='pdf_contract',
        ),
        migrations.AlterField(
            model_name='contract',
            name='object',
            field=ckeditor.fields.RichTextField(verbose_name='Object'),
        ),
        migrations.CreateModel(
            name='UploadContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_contract', models.FileField(blank=True, max_length=200, upload_to='upload_contract/', verbose_name='File')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('contract', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='upload_contract_contract_created_id', to='provider.provider', verbose_name='Contract')),
                ('user_created', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='upload_contract_user_created_id', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('user_updated', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='upload_contract_user_updated_id', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'Upload Contract',
                'verbose_name_plural': 'Upload Contracts',
                'ordering': ['updated_at'],
            },
        ),
    ]
