# Generated by Django 3.2 on 2021-06-28 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0010_alter_uploadcontract_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadcontract',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True, verbose_name='Slug'),
        ),
    ]
