# Generated by Django 3.2 on 2021-06-28 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_company_status'),
        ('contract', '0012_auto_20210628_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractcompany',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cc_company', to='company.company', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='contractcompany',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cc_contract', to='contract.contract', verbose_name='Contract'),
        ),
    ]
