# Generated by Django 3.2 on 2021-06-29 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_company_status'),
        ('contract', '0014_remove_contract_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='members_contract',
            field=models.ManyToManyField(through='contract.ContractCompany', to='company.Company', verbose_name='Contract Companies'),
        ),
        migrations.AlterField(
            model_name='contractcompany',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cc_company', to='company.company', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='contractcompany',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cc_contract', to='contract.contract', verbose_name='Contract'),
        ),
    ]
