# Generated by Django 3.2 on 2021-07-01 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0015_auto_20210628_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='dt_end',
            field=models.DateField(blank=True, max_length=100, null=True, verbose_name='Date End'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='dt_renovation',
            field=models.DateField(blank=True, max_length=100, null=True, verbose_name='Date Renovation'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='dt_start',
            field=models.DateField(blank=True, max_length=100, null=True, verbose_name='Date Initial'),
        ),
    ]
