# Generated by Django 3.2 on 2021-07-01 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_company_status'),
        ('contract', '0016_auto_20210630_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractcompany',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cc_company', to='company.company', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='uploadcontract',
            name='contract',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='upload_contract_contract_created_id', to='contract.contract', verbose_name='Contract'),
        ),
    ]
