# Generated by Django 3.2 on 2021-07-01 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0017_auto_20210701_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractcompany',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cc_contract', to='contract.contract', verbose_name='Contract'),
        ),
    ]
