# Generated by Django 3.2 on 2021-07-02 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0018_alter_contractcompany_contract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='dt_conclusion',
            field=models.DateField(blank=True, max_length=100, null=True, verbose_name='Date Conclusion'),
        ),
    ]
