# Generated by Django 3.2 on 2021-07-04 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0019_alter_contract_dt_conclusion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractcompany',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cc_contract', to='contract.contract', verbose_name='Contract'),
        ),
    ]
