# Generated by Django 3.2 on 2021-07-04 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0022_alter_contract_number_months'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='value_month',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Value Month'),
        ),
    ]
