# Generated by Django 3.2 on 2021-07-12 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0023_alter_contract_value_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='dt_renovation',
            field=models.DateField(blank=True, help_text='Date renovatation or value readjustment yearly', max_length=100, null=True, verbose_name='Date Renovation'),
        ),
    ]
