# Generated by Django 3.2 on 2021-07-20 15:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contract', '0027_alter_contract_dt_renovation'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='dt_create_rc',
            field=models.DateField(blank=True, max_length=100, null=True, verbose_name='Create RC Date Nimbi'),
        ),
        migrations.AddField(
            model_name='contract',
            name='dt_send_nf_fiscal',
            field=models.DateField(blank=True, max_length=100, null=True, verbose_name='Send Date Fiscal'),
        ),
        migrations.AddField(
            model_name='contract',
            name='number_cod_nimbi',
            field=models.CharField(blank=True, max_length=100, verbose_name='Number Cod Nimbi'),
        ),
        migrations.AddField(
            model_name='contract',
            name='number_cod_project',
            field=models.CharField(blank=True, max_length=100, verbose_name='Number Cod Project'),
        ),
        migrations.AddField(
            model_name='contract',
            name='number_cost_center',
            field=models.CharField(blank=True, max_length=100, verbose_name='Number Cost  Center'),
        ),
        migrations.AddField(
            model_name='contract',
            name='number_pc_nimbi',
            field=models.CharField(blank=True, max_length=100, verbose_name='Number PC Nimbi'),
        ),
        migrations.AddField(
            model_name='contract',
            name='number_req_nimbi',
            field=models.CharField(blank=True, max_length=100, verbose_name='Number Requisition Nimbi'),
        ),
        migrations.CreateModel(
            name='CostCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.CharField(max_length=100, verbose_name='Cod')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('branch', models.CharField(max_length=100, verbose_name='Branch')),
                ('plant', models.CharField(max_length=100, verbose_name='Plant')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='Slug')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('user_created', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='cost_center_user_created_id', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('user_updated', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='cost_center_user_updated_id', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'Cost Center',
                'verbose_name_plural': 'Costs Center',
                'ordering': ['cod'],
            },
        ),
    ]
