# Generated by Django 3.2 on 2021-07-21 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0029_auto_20210720_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='nimbicontract',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
    ]
