# Generated by Django 3.2 on 2021-07-21 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0030_nimbicontract_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='annual_budget',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=100, verbose_name='Annual Budget'),
        ),
    ]
