# Generated by Django 3.2 on 2021-08-04 23:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_department'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contract', '0033_auto_20210802_1132'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='Slug')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_contract', to='contract.contract', verbose_name='Contract')),
                ('number_cost_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_cost_center', to='company.department', verbose_name='Cost Center')),
                ('user_created', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='department_contract_user_created_id', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('user_updated', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='department_contract_user_updated_id', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'Department Contract',
                'verbose_name_plural': 'Department Contracts',
                'ordering': ['contract'],
            },
        ),
    ]
