# Generated by Django 3.2 on 2021-08-05 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_department'),
        ('contract', '0034_departmentcontract'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nimbicontract',
            name='number_cost_center',
        ),
        migrations.AddField(
            model_name='contract',
            name='members_cost_center',
            field=models.ManyToManyField(blank=True, through='contract.DepartmentContract', to='company.Department', verbose_name='Cost Center'),
        ),
    ]
