# Generated by Django 3.2 on 2021-08-16 15:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contract', '0036_usercontract'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nimbicontract',
            name='number_cod_nimbi',
        ),
        migrations.AddField(
            model_name='contract',
            name='members_user',
            field=models.ManyToManyField(blank=True, related_name='members_user_contract', through='contract.UserContract', to=settings.AUTH_USER_MODEL, verbose_name='User Contract'),
        ),
        migrations.AddField(
            model_name='nimbicontract',
            name='number_pc_sap',
            field=models.CharField(blank=True, max_length=100, verbose_name='Number PC SAP'),
        ),
        migrations.AlterField(
            model_name='nimbicontract',
            name='number_pc_nimbi',
            field=models.CharField(blank=True, max_length=100, verbose_name='Number PC Nimbi'),
        ),
    ]
