# Generated by Django 3.2 on 2021-06-14 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax_invoice', '0002_auto_20210613_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxinvoice',
            name='forfeit_satus',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=100, null=True, verbose_name='Forfeit Status'),
        ),
        migrations.AlterField(
            model_name='taxinvoice',
            name='time_end',
            field=models.DateField(blank=True, max_length=100, null=True, verbose_name='Time End'),
        ),
        migrations.AlterField(
            model_name='taxinvoice',
            name='time_start',
            field=models.DateField(blank=True, max_length=100, null=True, verbose_name='Time Start'),
        ),
        migrations.AlterField(
            model_name='taxinvoice',
            name='value_forfeit',
            field=models.DecimalField(blank=True, decimal_places=2, default='0,00', max_digits=20, null=True, verbose_name='Value Forfeit'),
        ),
    ]
