# Generated by Django 3.2 on 2021-06-16 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tax_invoice', '0003_auto_20210613_2106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taxinvoice',
            old_name='forfeit_satus',
            new_name='forfeit_status',
        ),
    ]
