# Generated by Django 3.2 on 2021-06-16 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax_invoice', '0004_rename_forfeit_satus_taxinvoice_forfeit_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxinvoice',
            name='ref_month',
            field=models.CharField(help_text='Formato: DDAAAA', max_length=7, verbose_name='Reference Month'),
        ),
        migrations.AlterField(
            model_name='taxinvoice',
            name='telecom_data',
            field=models.CharField(blank=True, help_text='Campo utlizado para Contratos de telecomunicações.', max_length=100, verbose_name='Telecom Data'),
        ),
    ]
