# Generated by Django 3.2 on 2021-06-17 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax_invoice', '0007_alter_taxinvoice_forfeit_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxinvoice',
            name='pay_day',
            field=models.DateField(blank=True, default='1950-01-01', max_length=100, verbose_name='Payment Day'),
        ),
    ]
