# Generated by Django 3.2 on 2021-06-18 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax_invoice', '0009_auto_20210617_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxinvoice',
            name='pay_day',
            field=models.DateField(blank=True, max_length=100, null=True, verbose_name='Payment Day'),
        ),
    ]
