# Generated by Django 3.2 on 2021-07-01 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_company_status'),
        ('tax_invoice', '0010_alter_taxinvoice_pay_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxinvoice',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='tax_invoice_company_created_id', to='company.company', verbose_name='Company'),
        ),
    ]
