# Generated by Django 3.2 on 2021-07-02 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax_invoice', '0011_taxinvoice_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxinvoice',
            name='dt_create_rc',
            field=models.DateField(blank=True, max_length=100, verbose_name='Create RC Date Nimbi'),
        ),
        migrations.AlterField(
            model_name='taxinvoice',
            name='dt_send_nf_fiscal',
            field=models.DateField(blank=True, max_length=100, verbose_name='Send Date Fiscal'),
        ),
        migrations.AlterField(
            model_name='taxinvoice',
            name='number_cod_nimbi',
            field=models.CharField(blank=True, max_length=100, verbose_name='Number Cod Nimbi'),
        ),
        migrations.AlterField(
            model_name='taxinvoice',
            name='number_cod_project',
            field=models.CharField(blank=True, max_length=100, verbose_name='Number Cod Project'),
        ),
        migrations.AlterField(
            model_name='taxinvoice',
            name='number_cost_center',
            field=models.CharField(blank=True, max_length=100, verbose_name='Number Cost  Center'),
        ),
        migrations.AlterField(
            model_name='taxinvoice',
            name='number_pc_nimbi',
            field=models.CharField(blank=True, max_length=100, verbose_name='Number PC Nimbi'),
        ),
        migrations.AlterField(
            model_name='taxinvoice',
            name='number_req_nimbi',
            field=models.CharField(blank=True, max_length=100, verbose_name='Number Requisition Nimbi'),
        ),
    ]
