# Generated by Django 3.2 on 2021-07-02 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax_invoice', '0012_auto_20210702_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxinvoice',
            name='dt_create_rc',
            field=models.DateField(blank=True, max_length=100, null=True, verbose_name='Create RC Date Nimbi'),
        ),
        migrations.AlterField(
            model_name='taxinvoice',
            name='dt_send_nf_fiscal',
            field=models.DateField(blank=True, max_length=100, null=True, verbose_name='Send Date Fiscal'),
        ),
        migrations.AlterField(
            model_name='taxinvoice',
            name='telecom_data',
            field=models.CharField(blank=True, help_text='Field used for telecommunications contracts..', max_length=100, verbose_name='Telecom Data'),
        ),
    ]
