# Generated by Django 3.2 on 2021-07-04 16:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tax_invoice', '0013_auto_20210702_1152'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadTaxInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_tax_invoice', models.FileField(blank=True, max_length=200, upload_to='upload_tax_invoice/', verbose_name='File')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='Slug')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('tax_invoice', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='upload_tax_invoice', to='tax_invoice.taxinvoice', verbose_name='Tax Invoice')),
                ('user_created', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='upload_tax_invoice_user_created_id', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('user_updated', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='upload_tax_invoice_user_updated_id', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'Upload Tax Invoice',
                'verbose_name_plural': 'Upload Tax Invoice',
                'ordering': ['updated_at'],
            },
        ),
    ]
