# Generated by Django 3.2 on 2021-07-04 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tax_invoice', '0014_uploadtaxinvoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxinvoice',
            name='pdf_invoice',
        ),
    ]
