# Generated by Django 3.2 on 2021-07-20 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tax_invoice', '0015_remove_taxinvoice_pdf_invoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxinvoice',
            name='dt_create_rc',
        ),
        migrations.RemoveField(
            model_name='taxinvoice',
            name='dt_send_nf_fiscal',
        ),
        migrations.RemoveField(
            model_name='taxinvoice',
            name='number_cod_nimbi',
        ),
        migrations.RemoveField(
            model_name='taxinvoice',
            name='number_cod_project',
        ),
        migrations.RemoveField(
            model_name='taxinvoice',
            name='number_cost_center',
        ),
        migrations.RemoveField(
            model_name='taxinvoice',
            name='number_pc_nimbi',
        ),
        migrations.RemoveField(
            model_name='taxinvoice',
            name='number_req_nimbi',
        ),
    ]
