BBBB BBBBBB
BBBB BBBBBBBBBBBBBBBBB

XXXXXXXXX XXXXX
XXXXX XXXXXXXXXXXXX

XXXXXX
    XXXXX XXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
    XXXX XXX XXXXX X XXXX XXXX XXXXXX XXXX XXXXX XX XXX XXXXX XXX XXXXX XXXX XXXXXXX XXXX XXXX XXXXXXX XXXXX XXXX XXX

    XXXX XXXXX XXX
    XXXXXXX XXXXXXXX XX X XXXXXXXX XXXXXXXX

    XXXX XXXXXXX XXX    
    XXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXX

    XXXX XXXX XXXXXXXXXX XXX    
    XXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXX

    XXXX XXXXXXXXXX XXXXXXXXXX XXX    
    XXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXX

XXXXXXX

XXXXXX

    XXXX XXXXXXXXXXXXXXXXXXXXX       

        XXXX XXXXXXX XXX
        XXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXX
                        XXXX XXXXXX XXX XXX
                        XXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX
                           
                            XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBX XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX
                            XXXXXXXXXXXXX X XXXXXXXXX
                            XXXXXXXX XXXXXXX
                            XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX
                                BBBBBBBBBB
                            
                                FFFFFF
                                XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                                XX XXXXXXBBB BBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXX                                
                            XXXXXXX
                            XX XXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXX XX XXXXXXX
                            XXXX XXXX XXX                           
                        XXXXXX
                    XXXXXX
                XXXXXX
            XXXXXX
        XXXXXX

        XXXX XXXXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXX
                    XXXX XXXXXXXXX XXXX XXX
                    XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXX
                        XXXXXX XXXXXX XXXXXXX XX XX XXXXXXXXXXXX XXXXXXXXXXXX                        
                    XXXXXX
                XXXXXX
            XXXXXX
        XXXXXX
    XXXXXX

     XXXX XXXXXX XXXXX XXX    
     XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
     XXXX XXXXXXXX XX XXX    
     XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX    
     XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX    
     XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
     XXXX XXXXXX XX XXX    
     XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBXXXXXXXXXXX

XXXXXXX

XXXXXXX

    