BBBBBBB BBBBBBBBBBBBBBBB
BBBB BBBBBBBBBBBBBBBBB

BBBBB BBBBB
XXXXX XX XXXXX
BBBBBBBB BBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXX
        XXX XXXXX XX XXXXX XXX
            XXXXX XXXXXXXXXXXXXX
                BBBBBBBBBB
                FFFFFF                
                XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXX
    XXXXXX
XXXXXX
BBBBBBBB BBBBBBB