BBBB BBBBBB

XXXX XXXX XXX XXX XXXX XXX
XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXX XXXXXXX XXXX XXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXX

        XXXX XXXX XXX
        XX XXXXXXXX XXXXXXXXXXX XXXXXX
            XXXXX XXXXXXXXXXXXXXXXX                       
                XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBX XXXXXXX
            XXXXXXX       
        XXXX
    XXXXXX

    XXXX XXXX XXXX XXX
    XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXX XXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXX
            XXXXXX

            XXXX XXXXXXXX XXXX XXX
            XXXX XXXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXX XXXX XXXX XXX
               
                   
                    XXXXX XXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBBBBBBXX
                        BBBBBBBBBB
                        XXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXX
                        XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX          
                        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX  
                             XXXX XXXXX XXX
                            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBX XXXXXXX
                            XXXXXX     
                             XXXX XXXXXXX XXXX XXX
                            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
                                XXXXXXXXXXXXXXXXX
                            XXXXXX                                   
                        XXXXXXXXX
                    XXXXXXX
                   
                

               
                    
                    XXXXX XXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBBBBBBXX
                        BBBBBBBBBB
                        XXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXX
                        XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX          
                        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX  
                            XXXX XXXXX XXX
                            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBX XXXXXXX
                            XXXXXX      
                             XXXX XXXXXXX XXXX XXX
                            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
                                XXXXXXXXXXXXXXXX
                            XXXXXX                                   
                        XXXXXXXXX
                    XXXXXXX                
            XXXXXX
        XXXXXX        

        XXXX XXXXXXXXXXXXX XXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX                            
                XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXX
            XXXXXX         
            XXXX XXXXXXXXXXXXX XXXX XXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXX XXX XXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXX XXXX XXXX XXX
                XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
                    XXXX XXXXXXXXXXXXX XXXX XXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XX XXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXX
                    XXXX XXXXXXXXXXXXX XXXX XXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXXXXX XXXX XXXXXXXXXXXXXXXX
                        XXXXXXXXXX XX XXXXX XXXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXXX
                    XXXXXX
                XXXX
                XXXX XXXXXXXXXXXXX XXXX XXXX XXX
                XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
                    XXXX XXXXXXXXXXXXX XXXX XXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XX XXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXX
                    XXXX XXXXXXXXXXXXX XXXX XXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXXX XXXX XXX X XXXXXXXXX XXXXX
                        XXXXXXXXXX XX XXXXX XXXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXXX
                    XXXXXX
                XXXX
                XXXX XXXXXXXXXXXXX XXXX XXXX XXX
                XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
                    XXXX XXXXXXXXXXXXX XXXX XXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XX XXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXX
                    XXXX XXXXXXXXXXXXX XXXX XXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXXXXXX XXXXXXXXXXXXXX
                        XXXXXX XXXXXXX
                    XXXXXX
                XXXX
                XXXX XXXXXXXXXXXXX XXX XXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XX XXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXXX
                XXXXXX
            XXXXXX
        XXXXXX                    

        XXXX XXXXXXX XXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXX XXX
            XXXX XXXXXXXXXXXXXXXXXXXXX                            
                XX XXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX
            XXXX XXXXXXX XXXX XXX
            XXXX XXXXXXXXXXXXXXXXXXXXX               
                XXXX XXXXXXX XXXX XXXX XXX
                XX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBXX
                    XXXX XXXXXXX XXXX XXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XX XXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXX
                    XXXX XXXXXXX XXXX XXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
                        XXXXXXXXXXX XXXXXXXXXX
                    XXXXXX
                XXXX
                XXXX XXXXXXX XXXX XXXX XXX
                XX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBXX
                    XXXX XXXXXXX XXXX XXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XX XXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXX
                    XXXX XXXXXXX XXXX XXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
                        XXXXXXX XXXXXXXX
                    XXXXXX
                XXXX
            XXXXXX
        XXXXXX
    XXXXXX
XXXXXX

