BBBB BBBB
XXXX XXXXXX XXX
XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX
    XXXX XXXXXX XXXX XXX
    XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX

        XXXX XXXXXX XXXXXXX XXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX

        XXXX XXXX XXX
        XXXX XXXXXXXXXXXXXXXXXXXX

            XXXX XXXXX XXX XXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX

            XXXX XXX XXXXX XXX
            XXXX XXXXXXXXXXXXXXXXXX
                XXX XXXXXXXXX
                    XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX  gettext(u'Register') XXXX
                        XXX XXXXXXXXXXXXXXX XXXXXXXX
                            XXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBXXX  gettext(u'Companies') XXXXXXXXX
                            XXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXX  gettext(u'Providers') XXXXXXXXX
                            XXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXX  gettext(u'Service Types') XXXXXXXXX
                            XXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBXXX  gettext(u'Status') XXXXXXXXX
                        XXXXX
                    XXXXX
                    XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX  gettext(u'Contracts') XXXX
                        XXX XXXXXXXXXXXXXXX XXXXXXXX
                            XXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXX  gettext(u'List Contracts') XXXXXXXXX
                            XXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXX  gettext(u'Create Contracts') XXXXXXXXX
                            XXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXX  gettext(u'Contracts Inactives') XXXXXXXXX                            
                        XXXXX
                    XXXXX                               
                    XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX  gettext(u'Tax invoices') XXXX
                        XXX XXXXXXXXXXXXXXX XXXXXXXX
                            XXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXX  gettext(u'Create Tax Invoice') XXXXXXXXX
                            XXXXXX XXXXXXXXX  gettext(u'Search Tax invoices') XXXXXXXXX                            
                        XXXXX
                    XXXXX                                                                
                    XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
                        XXX XXXXXXXXXXXXXXX XXXXXXXX
                            XXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXX
                            XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                            XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXX
                            XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXX XXXXXXXXXXXXX
                            XXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                        XXXXX
                    XXXXX                                
                XXXXX

            XXXXXX
            XXXX XXX XXX XXX
        XXXXXX
    XXXXXX
XXXXXX

