BBBB BBBBBB

XXXXXXXXX XXXXX
XXXXX XXXXXXXXXXXXX

XXXXXX
    XXXXX XXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
    XXXX XXX XXXXX X XXXX XXXX XXXXXX XXXX XXXXX XX XXX XXXXX XXX XXXXX XXXX XXXXXXX XXXX XXXX XXXXXXX XXXXX XXXX XXX

    XXXX XXXXX XXX
    XXXXXXX XXXXXXXX XX X XXXXXXXX XXXXXXXX

    XXXX XXXXXXX XXX    
    XXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
    
    XXXX XXX XXX XXXX XXX    
    BBBBB BBB BBBBBBBB
    
    XXXX XXXX XXXXXXXXXX XXX    
    XXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXX

    XXXX XXXXXXXXXX XXXXXXXXXX XXX    
    XXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXX

XXXXXXX

XXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXX XXXXXX XXXX XXXXX XXXXX XXX
        XXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXX

            BBBBBBB BBBBBBBBBBBBBBBBBBB 
            BBBBBBB BBBBBBBBBBBBBBBBBBB 
        XXXXXXXXX
        XXXX XXXXX XXXXXX XXXX XXX XXXXX XXX       

        XXXX XXXXXXX XXX
        XXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXX
                    BBBBB BBBBBBB
                    BBBBBBBB BBBBBBB
                XXXXXX
            XXXXXX
        XXXXXX

        XXXX XXXXXXXXXXXXXXXXXXXXXXXX
            BBBBBBB BBBBBBBBBBBBBBBBBBB 
        XXXXXX
    XXXXXX

    XXXX XXXXXX XXXXX XXX    
    XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
    XXXX XXXXXXXX XX XXX    
    XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX    
    XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
    XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
    
    XXXX XXXXXXX XX XXX
    XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
    XXXX XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX XXX    

    XXXX XXXXXXXX XX XXX
    XXXX XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX XXX    

    XXXX XX XXX XXXX XXX    
    BBBBB BB
    BBBBBBBB BB    
   
    XXXX XXXXXX XX XXX    
    XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
    

XXXXXXX

XXXXXXX