# Generated by Django 3.2 on 2021-06-04 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_provider', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactprovider',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
    ]
