# Generated by Django 3.2 on 2021-07-02 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0002_alter_provider_image'),
        ('contact_provider', '0002_alter_contactprovider_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactprovider',
            name='provider_id',
        ),
        migrations.AddField(
            model_name='contactprovider',
            name='provider',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='provider.provider', verbose_name='Provider'),
        ),
    ]
