# Generated by Django 3.2 on 2021-07-02 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0002_alter_provider_image'),
        ('contact_provider', '0003_auto_20210701_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactprovider',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provider.provider', verbose_name='Provider'),
        ),
    ]
