# Generated by Django 3.2 on 2021-07-31 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0032_alter_contract_pay_day'),
        ('contact_provider', '0004_alter_contactprovider_provider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactprovider',
            name='provider',
        ),
        migrations.AddField(
            model_name='contactprovider',
            name='contract',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contract.contract', verbose_name='Contract'),
        ),
        migrations.AddField(
            model_name='contactprovider',
            name='email_1',
            field=models.EmailField(blank=True, max_length=100, verbose_name='Main Email'),
        ),
        migrations.AddField(
            model_name='contactprovider',
            name='email_2',
            field=models.EmailField(blank=True, max_length=100, verbose_name='Secundary Email'),
        ),
    ]
